### ISSUE TITLE
Number of priors must match number of location predictions

### ISSUE THREAD

**Issue by anzisheng** [julimueller/tl_ssd#10]
Hello:
I have compiled the code according to readme sucessfully.
But when I run the ssd_dtld_test.py , I meet the error:
`F0215 12:27:08.644311 15733 detection_output_layer.cpp:164] Check failed: num_priors_ * num_loc_classes_ * 4 == bottom[0]->channels() (220472 vs. 110236) Number of priors must match number of location predictions.`
anyone can help me solve the problem?

**Comment by julimueller** [comment]
Do you use the DTLD dataset for testing or do you use your own input image? The input size should be 2048x512, the same as the input data size you can see in the prototxt. If not, you need to change both, input image size as well as the prototxt.

**Comment by anzisheng** [comment]
Yes, I use DTLD dataset for test and I didn't change  deploy.prototxt.
But when the code run at caffe.Net(), it raise the above exception.
