### ISSUE TITLE
"caffe.PriorBoxParameter" has no field named "offset_w".`

### ISSUE THREAD

**Issue by anzisheng** [julimueller/tl_ssd#11]
I use DTLD dataset for test and I didn't change  deploy.prototxt anf caffemodel.
But when the ssd_dtld_test.py run at caffe.Net(), it raise the  exception:
`[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 3668:13: Message type "caffe.PriorBoxParameter" has no field named "offset_w".`
Anyone can help me?

**Comment by lubill17** [comment]
> 
> 
> I use DTLD dataset for test and I didn't change deploy.prototxt anf caffemodel.
> But when the ssd_dtld_test.py run at caffe.Net(), it raise the exception:
> `[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 3668:13: Message type "caffe.PriorBoxParameter" has no field named "offset_w".`
> Anyone can help me?

same issue. Have you found the solution?

**Comment by julimueller** [comment]
Forgot to replace caffe.proto?

lubill17 <notifications@github.com> schrieb am So., 3. Jan. 2021, 03:48:

**Comment by lubill17** [comment]
right. i didn't notice that. thanks for your reply.

Am So., 3. Jan. 2021 um 17:48 Uhr schrieb Julian Müller <
notifications@github.com>:
