### ISSUE TITLE
Why we use raw_scale in preprocessing?

### ISSUE THREAD

**Issue by yucedagonurcan** [julimueller/tl_ssd#17]
Hello everyone,

Thank you for this repo first of all.
- I am confused why we are using pure ssd prepocessing, especially raw_scale which is 255: https://github.com/weiliu89/caffe/blob/4817bf8b4200b35ada8ed0dc378dceaf38c539e4/python/caffe/io.py#L223
- As far as I know, it is used for images represented in [0...1] range to scale them up to [0...255].

- I double checked using DTLD data and pixel ranges are [0...255]. So by using this raw_scale we end up with odd values for images:
```
array([[[11730., 11730., 11730., ...,  9435.,  8415.,  8415.],
        [11730., 11730., 11730., ...,  9435.,  8415.,  8415.],
        [11730., 11730., 11475., ...,  9180.,  9945.,  9945.],
        ...,
        [10200., 10200., 10965., ...,  6885.,  6885.,  6885.],
        [10200., 10200., 10200., ...,  6120.,  5865.,  5865.],
        [ 9945.,  9945.,  9690., ...,  5100.,  5100.,  5100.]],

       [[10455., 10455., 10965., ..., 16575., 13770., 13770.],
        [10455., 10455., 10965., ..., 16575., 13770., 13770.],
        [ 9690.,  9690.,  9435., ..., 14280., 15300., 15300.],
        ...,
        [10455., 10455., 10200., ..., 11220., 10455., 10455.],
        [10200., 10200.,  9945., ...,  9435.,  8670.,  8670.],
        [10455., 10455., 10200., ...,  7905.,  8415.,  8415.]],

       [[ 8160.,  8160.,  8160., ..., 13260., 13260., 13260.],
        [ 8160.,  8160.,  8160., ..., 13260., 13260., 13260.],
        [ 7650.,  7650.,  7650., ..., 10200., 13005., 13005.],
        ...,
        [ 8160.,  8160.,  8160., ...,  9435.,  9180.,  9180.],
        [ 8160.,  8160.,  8160., ...,  7905.,  7905.,  7905.],
        [ 8415.,  8415.,  8415., ...,  7140.,  7395.,  7395.]]],
      dtype=float32)

```

Forgive my curiosity, what am I missing here?

Have a great day.

**Comment by julimueller** [comment]
I think you are totally right that this makes no sense. Did you try whether it makes a difference at all? I quickly tested it but there was no difference.

**Comment by yucedagonurcan** [comment]
I tested many times and I didn't find anything changed about inference accuracy. 
Since it doesn't make a difference we can modify it.
