### ISSUE TITLE
Inference on different image sizes

### ISSUE THREAD

**Issue by yucedagonurcan** [julimueller/tl_ssd#18]
Hello,

I want to inference on difference dataset which consists of 256x512 images with pretrained model on repo.
Before that I tried with images 1024x768 and I found it very robust, but when I tried with 256x512 images its accuracy went nearly zero.

So if I want to inference on different image sizes, I am changing:

1. `ssd_dtld_test.py`
![code](https://user-images.githubusercontent.com/16342629/89717489-c4165400-d9bf-11ea-992e-443790975111.png)

2. `deploy.prototxt`
![code](https://user-images.githubusercontent.com/16342629/89717632-1e63e480-d9c1-11ea-8db0-40ae862a98b1.png)

So what should I do? Is there anything needs to be changed further?

Have a great day.

**Comment by julimueller** [comment]
There are various reasons for that. First of all: Are the 256x512 images resized in a manner that the traffic lights are distorted somehow (e.g. from aspect ratio 3 to something else)? What is the size distrubtion of the traffic lights? Are they all very small or is it similar to DTLD on which the TLs are trained on (think about the design of the prior boxes which are adapted to DTLD)? Maybe you can add one example image of your dataset.

Please do not forget to adapt the image mean before using the network on another dataset. DTLD had ~(60, 60, 60), I would try to change this value to the average value of the images you have from the new dataset.

Cheers

Julian
