### ISSUE TITLE
Message type "caffe.MultiBoxLossParameter" has no field named "state_digit".

### ISSUE THREAD

**Issue by zhaobaozi** [julimueller/tl_ssd#2]
Hi,
When i use the prior box adaptions AND state detection for DTLD,I meet "Error parsing text-format caffe.NetParameter: 3918:16: Message type "caffe.MultiBoxLossParameter" has no field named "state_digit".",but i have already replace the caffe file from you,what's the problem?
Thank you~

**Comment by julimueller** [comment]
Hi zhaobaozi,
you are right. I will take a look at that and inform you when i fixed it.
Best,
Julian

**Comment by julimueller** [comment]
Should be fixed now.

**Comment by zhaobaozi** [comment]
that's ok,
but i meet another problem when i want to train
`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 1)
*** Aborted at 1553237627 (unix time) try "date -d @1553237627" if you are using GNU date ***
`

what can i do?thanks!

**Comment by zhaobaozi** [comment]
that is ok.
but i meet another problem when i want to train

`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 1)
*** Aborted at 1553238223 (unix time) try "date -d @1553238223" if you are using GNU date ***

`
what can i do?Thanks!

**Comment by julimueller** [comment]
In which file (+ line) the error occurs?

**Comment by zhaobaozi** [comment]
when i run train ,the terminal can see:
`I0325 16:55:18.643296 156749 net.cpp:226] conv2_3x3_relu needs backward computation.
I0325 16:55:18.643301 156749 net.cpp:226] conv2_3x3_s1_scale needs backward computation.
I0325 16:55:18.643306 156749 net.cpp:226] conv2_3x3_s1_bn needs backward computation.
I0325 16:55:18.643311 156749 net.cpp:226] conv2_3x3_s1 needs backward computation.
I0325 16:55:18.643316 156749 net.cpp:226] conv1_3x3_relu needs backward computation.
I0325 16:55:18.643321 156749 net.cpp:226] conv1_3x3_s2_scale needs backward computation.
I0325 16:55:18.643326 156749 net.cpp:226] conv1_3x3_s2_bn needs backward computation.
I0325 16:55:18.643330 156749 net.cpp:226] conv1_3x3_s2 needs backward computation.
I0325 16:55:18.643337 156749 net.cpp:228] data_data_0_split does not need backward computation.
I0325 16:55:18.643343 156749 net.cpp:228] data does not need backward computation.
I0325 16:55:18.643347 156749 net.cpp:270] This network produces output mbox_loss
I0325 16:55:18.643353 156749 net.cpp:270] This network produces output mbox_state_sigmoid
I0325 16:55:18.643648 156749 net.cpp:283] Network initialization done.
I0325 16:55:18.644596 156749 solver.cpp:75] Solver scaffolding done.
I0325 16:55:18.659034 156749 caffe.cpp:251] Starting Optimization
I0325 16:55:18.659054 156749 solver.cpp:294] Solving SSD_DTLD_train
I0325 16:55:18.659060 156749 solver.cpp:295] Learning Rate Policy: step
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 1)
*** Aborted at 1553504118 (unix time) try "date -d @1553504118" if you are using GNU date ***
PC: @     0x7f2dbb989428 gsignal
*** SIGABRT (@0x2644d) received by PID 156749 (TID 0x7f2dbe348b00) from PID 156749; stack trace: ***
    @     0x7f2dbb9894b0 (unknown)
    @     0x7f2dbb989428 gsignal
    @     0x7f2dbb98b02a abort
    @     0x7f2dbc79d84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f2dbc79b6b6 (unknown)
    @     0x7f2dbc79b701 std::terminate()
    @     0x7f2dbc79b919 __cxa_throw
    @     0x7f2dbc7c43f7 std::__throw_out_of_range_fmt()
    @     0x7f2dbd8c480f caffe::GetGroundTruth<>()
    @     0x7f2dbda699f0 caffe::MultiBoxLossLayer<>::Forward_cpu()
    @     0x7f2dbd8ff3f7 caffe::Net<>::ForwardFromTo()
    @     0x7f2dbd8ff767 caffe::Net<>::Forward()
    @     0x7f2dbd94cb40 caffe::Solver<>::Step()
    @     0x7f2dbd94d5ce caffe::Solver<>::Solve()
    @           0x40bd14 train()
    @           0x4077e8 main
    @     0x7f2dbb974830 __libc_start_main
    @           0x4080b9 _start
    @                0x0 (unknown)
train.sh: line 4: 156749 Aborted                 (core dumped) build/tools/caffe train -solver="tl_ssd/prototxt/solver.prototxt" -gpu=0

`
