### ISSUE TITLE
forward pass got killed

### ISSUE THREAD

**Issue by lubill17** [julimueller/tl_ssd#21]
hello Julian Müller,

i'm trying to run the demo with CPU. Unfortunately, it was interrupted during forward pass. Do I have to use GPU for it? Thanks in advance.

MfG.

![Unbenannt](https://user-images.githubusercontent.com/76891571/103471375-9c82b680-4dba-11eb-8f61-b0050bf7f4a1.png)

**Comment by lubill17** [comment]
seems to be caused by memory. 
However, now i got ("IndexError: index 9 is out of bounds for axis 3 with size 7") as well....
![Unbenannt](https://user-images.githubusercontent.com/76891571/103471643-a35ef880-4dbd-11eb-92d8-6e035a259816.png)

**Comment by julimueller** [comment]
This is very likely not an issue of memory. Did you replace all files of the output layer, i.e.

- detection_output_layer.hpp
- detection_output_layer.cpp
- detection_output_layer.cu
?

I think I got the problem. I never changed the implementation of detection_output_layer.cpp to also output the state confidences. It is only covered in the .cu file, which is executed when running it on GPU. When you run the CPU mode, the detection output layer will only output the detection confidences and box coordinates without state and the python module expects a larger output (with state). So either you change the python module, or you try to understand whats going on in the .cu file and adapt the .cpp according to that. Or you need a GPU to run it in GPU mode, then it should run out of the box. Sorry for the issues.

**Comment by lubill17** [comment]
works fine with GPU. Thank you for the excellent job!

Am So., 3. Jan. 2021 um 18:33 Uhr schrieb Julian Müller <
notifications@github.com>:
