### ISSUE TITLE
Do we need the labelmap.prototxt file when we use the class "112340" as the label as you mentioned in training phase?

### ISSUE THREAD

**Issue by Morgan-117** [julimueller/tl_ssd#7]
I want to prepared the DTLD dataset for training the model, I think I can use the class label(e.g. 112340) in the txt directly as you recommended. And then using lmdb format data created from lists of .jpg and .txt.  So I don't need to using the labelmap file. 
By the way, do you use the same method for data augmentation as the original SSD? It will help a lot if  you could share your data layer in your train.prototxt.

**Comment by julimueller** [comment]
I also trained the network using LMDB format. You do not need the labelmap file. 
I do mean substraction (should be approximately (60,60,60)), and distortion (contrast , saturation, hue) as preprocessing.

**Comment by Morgan-117** [comment]
Thanks for your help, I will try

**Comment by Morgan-117** [comment]
Do you prepare the dataset  like SSD(creat_data.sh, creat_annoset.py and convert_annoset)?  In this way,I think we need a labelmap.prototxt file to convert the "112340"label to 4.

**Comment by julimueller** [comment]
Please check bbox_util.cpp:

` int state_digit_nr = 4;
state = digits.at(state_digit_nr);`

I extract the state from the complete classId
