### ISSUE TITLE
Layer mbox_loss error when only use the prior box adaptions

### ISSUE THREAD

**Issue by Morgan-117** [julimueller/tl_ssd#8]
when I use the original mbox_loss layer as you recommend, it print
```
I0613 03:33:26.476109 16066 net.cpp:434] mbox_state <- inception_b4_concat_norm_mbox_state_flat
I0613 03:33:26.476140 16066 net.cpp:408] mbox_state -> mbox_state
I0613 03:33:26.476225 16066 net.cpp:150] Setting up mbox_state
I0613 03:33:26.476246 16066 net.cpp:157] Top shape: 8 165354 (1322832)
I0613 03:33:26.476255 16066 net.cpp:165] Memory required for data: 19659154720
F0613 03:33:26.476299 16066 net.cpp:88] Check failed: layer_param.propagate_down_size() == layer_param.bottom_size() (5 vs. 4) propagate_down param must be specified either 0 or bottom_size times
```
But when I remove all the propagate_down_size param, it prints as following
```
I0613 04:03:53.034931 16106 net.cpp:100] Creating Layer mbox_loss
I0613 04:03:53.034948 16106 net.cpp:434] mbox_loss <- mbox_loc
I0613 04:03:53.034972 16106 net.cpp:434] mbox_loss <- mbox_conf
I0613 04:03:53.035014 16106 net.cpp:434] mbox_loss <- mbox_priorbox
I0613 04:03:53.035034 16106 net.cpp:434] mbox_loss <- label
I0613 04:03:53.035068 16106 net.cpp:408] mbox_loss -> mbox_loss
F0613 04:03:53.035151 16106 layer.hpp:374] Check failed: ExactNumBottomBlobs() == bottom.size() (5 vs. 4) MultiBoxLoss Layer takes 5 bottom blob(s) as input.
```
it occurs when I only use the prior box adaptions, and make all the boxes labels same to one class.  It seems that the mbox_loss layer must have 5 bottom Blobs.

**Comment by Morgan-117** [comment]
I find some confused code in *multibox_loss_layer.cpp*
```
  if (do_state_prediction_) {
      GetGroundTruth(gt_data, num_gt_, background_label_id_, use_difficult_gt_,
                     &all_gt_bboxes, do_state_prediction_);
  }
  else {
      GetGroundTruthState(gt_data, num_gt_, background_label_id_, use_difficult_gt_,
                     &all_gt_bboxes, state_digit_, background_state_id_);
  }

```
when you don't predict the tl state, you pass the state_digit_ to the function. I really appreciate  your reply.

**Comment by julimueller** [comment]
Hi Morgan,

your are correct, i also spotted these errors some weeks ago. Give me some time - will push a fixed version hopefully this week.

**Comment by Morgan-117** [comment]
Hi, Julian, sorry for asking for help. A strange error about detection_out occurs when I want to train the model with state prediction.
```
I0618 02:54:09.184280 17248 net.cpp:693] Ignoring source layer mbox_loss
I0618 02:54:09.323866 17288 annotated_data_layer.cpp:305] Prefetch batch: 137 ms.
I0618 02:54:09.323913 17288 annotated_data_layer.cpp:306]      Read time: 0.023 ms.
I0618 02:54:09.323923 17288 annotated_data_layer.cpp:307] Transform time: 117.293 ms.
F0618 02:54:09.575199 17248 detection_evaluate_layer.cpp:55] Check failed: bottom[0]->width() == 7 (13 vs. 7)
```
I looked into the detection_output_layer code, The top_shape's width should be 7, 
'''
  // num() and channels() are 1.
  vector<int> top_shape(2, 1);
  // Since the number of bboxes to be kept is unknown before nms, we manually
  // set it to (fake) 1.
  top_shape.push_back(1);
  // Each row is a 7 dimension vector, which stores
  // [image_id, label, confidence, xmin, ymin, xmax, ymax]
  top_shape.push_back(7);
  top[0]->Reshape(top_shape);
'''
So, do you have any ideas about this error?

**Comment by Morgan-117** [comment]
I think  the reason is in detection_output_layer.cu:
```
  // For multilabel we want to get all class confidences
  if(do_state_prediction_) {
      return_number = 4 + 3 + num_states_ ;
      top_shape.push_back(return_number);

  }
  // Else we only want the highest confidence
  else {
      return_number = 7;
      top_shape.push_back(7);
```
when GPU mode is using, it call the Forward_gpu, so maybe we need to turn the do_state_prediction flag to false when using GPU.

**Comment by julimueller** [comment]
Hi Morgan,

i never used the detection_EVALUATE_layer and it seems the error occurs here. However i can imagine why: when using the detection_output_layer with state prediction the top_shape width should be 7 + num_states, in my case i use the states off, red, yellow, green, red-yellow and background, so 7+6=13 should be correct. Without state prediction, the top shape width should be 7.
